sudo: required
language: c
services:
  - docker
script:
  - make
after_success:
  - eval $(docker run --rm -e APPROLE_ID=$APPROLE_ID -e APPROLE_SECRET=$APPROLE_SECRET vxlabs/vault-envexport)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY
  - export IMG=$DOCKER_REGISTRY/vxlabs/vault-envexport
  - docker tag vxlabs/vault-envexport $IMG:$TRAVIS_COMMIT
  - docker push $IMG:$TRAVIS_COMMIT;
  - docker tag $IMG:$TRAVIS_COMMIT $IMG:latest
  - docker push $IMG:latest
